version: '3'
services:
  calibre:
    container-name: calibre
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - calibre-config:/config
      - calibre-library:/library
      - <books>:/books:ro
volumes:
  calibre-config:
  calibre-library: